apiVersion: v1
kind: Service
metadata:
  name: go-app
  namespace: go-app
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: go-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  namespace: go-app
spec:
  selector:
    matchLabels:
      app: go-app
  replicas: 1
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: roweluchi/http_go:latest
        ports:
        - containerPort: 8080
